name: Docs2Pages
on:
  push:
    tags: '*'
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    #----------------------------------------------
    # poetry install
    #----------------------------------------------
    - name: poetry install
      uses: abatilo/actions-poetry@v2.1.6
      with: 
        poetry-version: "1.6.1"
    - name: testing install
      run : poetry --help
    #----------------------------------------------
    # install documentation dependencies
    #----------------------------------------------
    - name: install
      run: poetry install -E docs -vvv
    #----------------------------------------------
    # build documentation
    #----------------------------------------------
    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run make html
        cp -r _build/* ../gh-pages/        
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages